Add rate limit avoidance to MeetupClient.
abendig/django-meetup pull request #1
Opened 2017-08-24 05:50 UTC by rbevers

The existing client would hit rate limits if used for repeated Meetup calls in a short time frame. New logic added to MeetupClient will avoid it by thread sleeping until the rate limit time window is past.

2017-09-02 01:01 UTC, abendig requested changes
This breaks POST.

2017-09-02 01:01 UTC, abendig commented on meetup/api.py
> +        response = requests.post(url, data=kwargs).text
That leaves response as a string.

2017-09-02 01:01 UTC, abendig commented on meetup/api.py
> +            return response.json()
if response is a str it won't have a json() method

2017-09-02 01:01 UTC, abendig commented on meetup/api.py
>              return None
... and this will always be executed

2017-09-02 03:46 UTC, rbevers commented
Fix to the wrong response pattern. Ouch. :( Look better?

2017-09-13 01:59 UTC, abendig commented
We need to add proper test coverage of the changes, before merging this out.

2017-09-13 04:25 UTC, rbevers commented
Test coverage added in `test_api.py`. Runnable with:

    PYTHONPATH=$(pwd) python meetup/tests/test_api.py

2017-09-27 13:49 UTC, rbevers commented
@abendig Is this sufficient test coverage?

2017-09-29 18:32 UTC, abendig approved these changes
Let's ship!

2017-09-29 18:32 UTC, abendig commented on meetup/api.py
> +        if not params.has_key('page'):
_Slightly_ better: `if not "page" in params`

2017-09-29 18:32 UTC, abendig commented on meetup/tests/test_api.py
> +class MeetupClientTests(unittest.TestCase):
Thank you!

2017-10-03 19:38 UTC, rbevers commented
Ah, I forgot to merge. No merge button. Merging now.

2017-10-03 19:59 UTC, rbevers commented
Oh, I am not a contributor on your repo. Can I merge the dependency to point to `rbevers/django-meetup` or do you want to merge my PR to your repo?

2017-10-03 20:04 UTC, merged